### ISSUE TITLE
The preferences are saved only on Escape keypress, not on window close

### ISSUE THREAD

**Issue by jafd** [baverman/snaked#10]
This patch fixes the issue:

<pre><code>
diff --git a/snaked/core/gui/editor_prefs.py b/snaked/core/gui/editor_prefs.py
index df10e17..ae51d29 100644
--- a/snaked/core/gui/editor_prefs.py
+++ b/snaked/core/gui/editor_prefs.py
@@ -12,6 +12,7 @@ class PreferencesDialog(BuilderAware):
         BuilderAware.__init__(self, join_to_file_dir(__file__, 'editor_prefs.glade'))
         self.activator = shortcuts.ShortcutActivator(self.window)
         self.activator.bind('Escape', self.hide)
+        self.window.connect('delete_event', lambda widget, event: self.hide())
 
         self.prefs = prefs
         self.original_prefs = prefs.copy()
</code></pre>

**Comment by baverman** [comment]
I missed signal in glade file. But thanks anyway. New release was uploaded to PYPI.
