### ISSUE TITLE
FR: switch tabs with GConf-defined shortcut if running under GNOME

### ISSUE THREAD

**Issue by jafd** [baverman/snaked#12]
For example, all other tabbed programs (gnome-terminal, firefox, gedit) use Ctrl-Page Up/Ctrl-Page Down for cycling between tabs. Snaked makes you re-learn old habits which is quite painful, just like going from a Mac with Cmd-everything to Linux with Ctrl-everything using the same keyboard.

Unfortunately, I don't know how to implement that cleanly, so cannot provide a patch :-(

**Comment by baverman** [comment]
These shortcuts confuse me all time. Semantically they mean Up/Down, but should do Left/Right. Anyway there is always Shortcut Manager. But I can hardcode additional keybindings. I don't want to use DE specific features.

**Comment by baverman** [comment]
implemented
