### ISSUE TITLE
FR: hide tab bar with a keyboard shortcut

### ISSUE THREAD

**Issue by jafd** [baverman/snaked#13]
How about hiding the tab bar but retain the tabs themselves and stay able to cycle between them on keyboard? Would be a killer in full screen.

**Comment by baverman** [comment]
The main problem is how to distinguish editors. When I see tab titles I can press shortcut needed number of times mechanically. But in case of hided tabs I need to look at editor's content. May be tabs should be shown temporarily? Some sort of 'autohide tab bar' feature?

**Comment by jafd** [comment]
I doubt it. I use Firefox's F11 mode (without the tabbar) extensively, and it comes out that tabs order is remarkably easy to remember; once I know which file I'm at, I remember how many times to switch and which way to get to the file I want to.

I also used to use Emacs' buffer cycling (C-x right and C-x left) with tabbar hidden for several years now, and it takes only a minute or two to remember the order of files, then you're getting to them fast as hell.

Hence the whole request; if anyone has a bad memory for his session, he's free not to use the mode at all.

(Now the question comes as whether to make this into a plugin, so that it can be disabled altogether.)

**Comment by baverman** [comment]
Ok. Assigned.

**Comment by baverman** [comment]
Implemented via --hide-tabs option or Alt+F11 shortcut.
