### ISSUE TITLE
FR: editor shortcuts to follow unix-way

### ISSUE THREAD

**Issue by jafd** [baverman/snaked#14]
Wouldn't it be awesome if Snaked had a way to define macros of the following kinds?

1) run arbitrary command on the current selection, passing the selection as stdin and replace the selection with command's stdout.
2) run arbitrary command on the current buffer, passing its contents as stdin and replacing the buffer with results.
3) the same as 2), except that a new buffer is created and the command's stdout is placed there.

This would enable users to use their old and faithful tools, some even written in Perl, easily within the editor. Say, CVS-style keywords substitution, and no need to write your own Snaked-specific plugin.

I envision two ways of defining such macros: one with assigning a keyboard shortcut, and another assigning a name and having a shortcut like the (in)famous M-x of Emacs to invoke it.

Of course passing arguments would be nice but even a version without arguments would do greatly.

**Comment by baverman** [comment]
I think about tools plugin.

The only hard part is number of actions:
- simply run command with expanded current file name or directory
- pipe buffer/selection

Each of this variants have following results
- silent run
- show console with stdout
- replace buffer/selection
- open new buffer (this conflicts with snaked design: all buffers must have corresponding filename)

These cases are covered with vim implementation and it's command mode. Have you any GUI solutions?

**Comment by jafd** [comment]
Let's keep things really simple:
- pipe only
- replace buffrer/selection

which gives us 4 possible combinations.

An example of implementation is TextMate.

**Comment by baverman** [comment]
I'll look at TextMate's documentation to get idea.

**Comment by baverman** [comment]
Please, test external tools plugin.

Quick guide:
- Preferences can be found in 'Preferences dialog' Ctrl+P
- Name may contain pango markup and underline to define mnemonic for menu item.
- Langs is comma separated list of languages. May be empty if tool can be run against any editor.
- Command may contain %s, %d, %f variables. See appropriate tooltip for it's meaning.

Default shortcut to activate run menu is Alt+X.

I'am waiting for feedback.

**Comment by jafd** [comment]
Alt-X doesn't work. :-( 

It worked as of eight hours ago, but didn't run the command at all.

**Comment by baverman** [comment]
Any errors in console?

**Comment by jafd** [comment]
No errors in console, no tracebacks, no nothing. Just doesn't run the command (the command starts fine from a shell).

**Comment by jafd** [comment]
And by the way, Alt-X not working is the latest commit.

Did you push it to GH?

**Comment by baverman** [comment]
Plugin is enabled? Is there item in Preferences Dialog?

**Comment by jafd** [comment]
Yes, it is. Checked and rechecked. There is also my tool defined, just that Alt-X doesn't show the menu. When there's no tool, Alt-X gives feedback about no tools defined.

**Comment by baverman** [comment]
May be menu shown outside of screen? What window manager do you use? Have you multi-monitor setup?

**Comment by jafd** [comment]
No, it can't be outside the screen because it would have focus anyway. I press Alt-X and up/down arrows still navigate the document. Using Metacity on a single screen setup.

Checked both windowed and full-screen setup.

**Comment by baverman** [comment]
Under metacity I have similar behavior.

**Comment by baverman** [comment]
Damn, I reproduce it only once. Please, check out metacity branch. It logs menu coordinates to stdout.

**Comment by jafd** [comment]
There's another reason for this behavior.

Patch:

<pre><code>
diff --git a/snaked/plugins/external_tools/__init__.py b/snaked/plugins/external_tools/__init__.py
index faa6f73..f762ea3 100644
--- a/snaked/plugins/external_tools/__init__.py
+++ b/snaked/plugins/external_tools/__init__.py
@@ -23,10 +23,10 @@ def get_run_menu(prefs, editor):
     for tool in sorted(prefs):
         if prefs[tool]['stdin'] == 'selection' and not has_selection:
             continue
-            
-        if prefs[tool]['langs'] and editor.lang not in map(str.strip, prefs[tool]['langs'].split(',')):
+
+        if prefs[tool]['langs'] and editor.lang not in map(lambda x: x.strip(), prefs[tool]['langs'].split(',')):
             continue
-        
+
         any_items = True
         item = gtk.MenuItem(None, True)
         label = gtk.Label()
@@ -63,7 +63,7 @@ def run_tool(editor):
     if not menu:
         editor.message('There is no any tool to run')
         return
-        
+
     menu.popup(None, None, get_coords, 0, gtk.get_current_event_time())
 
 def on_item_activate(item, editor, prefs):
@@ -127,8 +127,8 @@ def run(editor, prefs):
     import shlex
     import os.path
     from subprocess import Popen, PIPE
-    
-    command = shlex.split(prefs['command'])
+
+    command = shlex.split(str(prefs['command']))
     if not command:
         editor.message('Tool must define command to run')
         return    
</code></pre>

**Comment by jafd** [comment]
In fact stdout was full of tracebacks, for some reason .xsession-errors didn't have them.

**Comment by baverman** [comment]
> In fact stdout was full of tracebacks

Can you post some of them?

**Comment by jafd** [comment]
For example:

<pre>
Traceback (most recent call last):
  File "/home/jafd/src/snaked/snaked/util/__init__.py", line 13, in idle_callback
    callable(*args, **kwargs)
  File "/home/jafd/src/snaked/snaked/plugins/external_tools/__init__.py", line 157, in run
    stdin=PIPE if stdin else None).communicate(stdin)
  File "/usr/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
</pre>

**Comment by jafd** [comment]
The first change was due to the fact that str.split doesn't apply to a unicode object and the preferences are unicode. The second one is due to the fact  that shlex.split screws badly any unicode input, so it must be encoded before passing to shlex.split.

Anyway, the patch works.

And yeah, I don't use Python 3, just in case.

**Comment by baverman** [comment]
Fix pushed. Thanks again.

**Comment by baverman** [comment]
My bad. I can not imagine that one can input non ascii chracters for command or langs.

**Comment by jafd** [comment]
In fact all my commands are pure-ascii, it's just that some modules expect strings and not unicode, or they accept unicode and produce garbage.

Moreover, json always produces unicode, still some of your code thinks those will be strings.

**Comment by baverman** [comment]
> Moreover, json always produces unicode

In python 2.7 it produces str for pure ascii strings.

**Comment by baverman** [comment]
Anyway, are there any suggestions to improve plugin functionality?
