### ISSUE TITLE
auto remove trailing whitespaces

### ISSUE THREAD

**Issue by imvalgo** [baverman/snaked#20]
Maybe snaked should clean whitespaces on save or by some keybind?

**Comment by baverman** [comment]
I use external tool with "sed 's/[ \t]*$//'" command for that task. External tool menu is called by Alt+X shortcut and you may define mnemonic key in tool name via underscore.

Anyway I'am going to implement this feature in nearest time.

**Comment by imvalgo** [comment]
Thank you! I will wait for next release)
