### ISSUE TITLE
FR: configurable filter for quick open

### ISSUE THREAD

**Issue by imvalgo** [baverman/snaked#23]
Most of time i don't want to open some files in project, such as  db migrations. Rope plugin allow to specify property 'ignored_resources', maybe quick-open should respect it?

**Comment by baverman** [comment]
There is quick_open ignore context in master. You may open File Types in Preferences (ctrl+P) and edit it. For example:

```
/migrations: quick_open:ignore
```

To ignore south django migrations.

**Comment by imvalgo** [comment]
Thank you!
