### ISSUE TITLE
FR: Multiple windows

### ISSUE THREAD

**Issue by bigdrum** [baverman/snaked#24]
I would like to edit 2 or more files side by side at the same time in tile wm. It seems snaked does not support multiple windows in one process. Although someone could open another window in a separate process, but the session is not shared so it is a bit pain to get everything in sync.

Also it would be nice to reload the file content when a editing file has been modified externally.

**Comment by baverman** [comment]
> It seems snaked does not support multiple windows in one process.

It's true, there is no windowed mode anymore since 42e56209cf724c82f6c9e9e7d6160f49015f4d50 due to technical problems with quick panels implementation.

> I would like to edit 2 or more files side by side

How about split window functionality like in vim or emacs?

> Also it would be nice to reload the file content when a editing file has been modified externally.

Ok.

**Comment by bigdrum** [comment]
+1 split window
thx ;)

**Comment by yescalona** [comment]
same problem when i use multiple workspaces

**Comment by baverman** [comment]
> same problem when i use multiple workspaces

Snaked is under heavy refactoring now. After that there will be split window as well as detachable tabs.

**Comment by baverman** [comment]
Implemented. v0.5dev has the ability to open multiple windows with the same buffers. Root menu -> Tab -> Detach.
