### ISSUE TITLE
FE: adjustable panel for plugins

### ISSUE THREAD

**Issue by bigdrum** [baverman/snaked#29]
I am writing an IPython console plugin. Currently I'm using the editor.add_widget_to_stack to embed the widget. It would be nice to make the panel size adjustable by the user.

**Comment by baverman** [comment]
> IPython console

I am also writing python repl from scratch, without using any existing backend. It will feature free editing of previous statements, autocomplete and runtime code update from changed project files. However, my plugin will be done at next week only.

> It would be nice to make the panel size adjustable by the user

Agreed.

**Comment by baverman** [comment]
Resizable pane was implemented.

**Comment by bigdrum** [comment]
Great. Just commited my current implementation, but I have not tested it on machines without IPython. I'm also going to implement a user module deleter(as seen in spyderlib) for runtime update.

Look forward to your new console (IPython might be bloated sometimes ;) )

**Comment by baverman** [comment]
I am very glad to see 3rd party plugins in snaked code. Thanks.

BTW, I look at plugin and did some minor fixes and dirty hack to overide runner current directory.

**Comment by baverman** [comment]
Adjourn for the prescription of years.
