### ISSUE TITLE
Ctrl-Y (redo) not working

### ISSUE THREAD

**Issue by hellp** [baverman/snaked#37]
The shortcut has no effect for me.

**Comment by baverman** [comment]
Yeah, default gtksourceview binding for "Redo" is Ctrl+Shift+Z. Perhaps I should make it customizable along with move-words feature.

**Comment by hellp** [comment]
Ah, thanks. Nice. Didn't knew that. In the docs you mention that it's Ctrl+Y. Maybe just change that ;)
