### ISSUE TITLE
Bracket matching color

### ISSUE THREAD

**Issue by skim** [baverman/snaked#46]
Can there be an option to change the bracket matching color? Or if you could give me a hint how to change it in the source code i'd do it myself, a quick hack would be enough for me. It's just that the bracket matching color distracts me too much ;)

**Comment by baverman** [comment]
> Can there be an option to change the bracket matching color?

Nope. I think all colors should be defined by highlight theme.

> could give me a hint how to change

The most easy way is to tweak gtksourceview style. You can find theme files in /usr/share/gtksourceview-2.0/styles. Find style tags for 'bracket-match' and 'bracket-mismatch', later may be not defined, and change colors for your needs. Changed style can be placed into ~/.local/share/gtksourceview-2.0/styles.

> it in the source code

I don't recommend this. But you can can assign custom colors in module 'snaked.plugins.edit_and_select.bracket_matcher' in 'get_tag' function, see tag.props assignments.

**Comment by skim** [comment]
Thanks, I thought it would be doable via themes, but I didn't know where to look for the theme configs (I'm not familiar with the gtksourceview widget). Thanks for the pointer!
