### ISSUE TITLE
TypeError when trying to show calltip

### ISSUE THREAD

**Issue by pevzi** [baverman/snaked#49]
Snaked successfully shows calltip only when an open bracket is put after the object name and the cursor is positioned after it. Otherwise, the following error occurs:

```
Traceback (most recent call last):
  File "/home/pevzi/src/snaked/snaked/plugins/python/plugin.py", line 158, in show_calltips
    sig, docstring = self.env.get_docstring(self.project_path, source, offset, self.editor.uri)
TypeError: 'NoneType' object is not iterable
```

**Comment by baverman** [comment]
Supplement gets dosctrings from a call context only, i.e., func(arg1, ar|) to resolve disambiguation with nested callables: func1(fun|c2).

**Comment by pevzi** [comment]
Ok, I see now. It was quite useful to get a docstring just pressing ctrl+enter «above» the function name but the new variant is much more practical.
