### ISSUE TITLE
FR: initial state of quick open dialog (without search term)

### ISSUE THREAD

**Issue by baverman** [baverman/snaked#5]
There should be two sections
1. Recent files (5 items? With expender for more recent files?)
2. Project directory with expenders to investigate project's structure.

**Comment by jafd** [comment]
At the very least, the dialog must give a clear idea of where we start. I was mildly confused, then relaunched snaked the old-fashioned way, passing filename as argument.

**Comment by baverman** [comment]
Think about this like ':q' during the very first vim run.

I did not found any solution to make dialog more intuitive without additional labels and buttons. Any suggestions? May be feedback message?

**Comment by baverman** [comment]
Browser mode implemented. There is no need in recent files.
