### ISSUE TITLE
Code completion partially failing with latest versions

### ISSUE THREAD

**Issue by fdev31** [baverman/snaked#51]
Using today's head of uxie, supplement & snaked:

Ctrl+Enter is bound to code "Show calltips" and it's not working at all (in fact, it looks like any shortcut involving "Return" is ineffective.
Once I changed the keybind, the feature is still not working, I get in the console the following trace:

```
Traceback (most recent call last):
  File "/home/fab31/progs/snaked/snaked/plugins/python/plugin.py", line 153, in show_calltips
    result = self.env.get_docstring(self.project_path, source, offset, self.editor.uri)
  File "/home/fab31/progs/supplement/supplement/remote.py", line 153, in get_docstring
    return self._call('get_docstring', project_path, source, position, filename)
  File "/home/fab31/progs/supplement/supplement/remote.py", line 93, in _call
    raise Exception(result)
Exception: ('AttributeError', "'listiterator' object has no attribute '__next__'")

```

**Comment by baverman** [comment]
Very strange. All changes are pushed and I have no any problems.

> object has no attribute '**next**'

Perhaps you install supplement from master into python3 environment. You should use py3 branch for that.

> in fact, it looks like any shortcut involving "Return" is ineffective.

Ctrl+Return is also bound to replace action. Check it out: find something or mark occurrences, then Ctrl+R, type text for replace and press Ctrl+Return. If it doesn't work then show me ~/.config/snaked/keys.conf.

Also check "Python/Show calltip" menu item has shortcut label.

**Comment by fdev31** [comment]
Interesting, I'm not on the same computer now but I had to remove .config/snaked to fix the behavior...
The remaining problems I see are:
- "Send to console" (Alt+Return) isn't working with the default keybind (Alt+C is OK)
- I can't find the regex or replace-all options in ^F^R
-  Pylint plugin:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/uxie/plugins.py", line 53, in add_plugin
    plugin.init(self.injector)
  File "/usr/lib/python2.7/site-packages/snaked/plugins/python_lint/__init__.py", line 13, in init
    manager.add_global_option('PYLINT_CHECK_ON_SAVE', False, 'Run pylint on every file save')
AttributeError: 'Injector' object has no attribute 'add_global_option'
```
- Goto dir plugin:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/uxie/plugins.py", line 53, in add_plugin
    plugin.init(self.injector)
  File "/usr/lib/python2.7/site-packages/snaked/plugins/goto_dir/__init__.py", line 6, in init
    injector.bind_accel('editor-active', 'goto-dir', 'File/Open file\'s directory#30',
AttributeError: 'Injector' object has no attribute 'bind_accel'
```
- the new (non ipython) console is quite interesting, code highlighting makes me think about a working completion but the "Where is your attached completer now ?" message sounds like "to be implemented" stuff...

Just tell me in case you need some tests.

**Comment by fdev31** [comment]
Forget my problems with ^F & ^R,
since the F1 menu is contextual I got lost ;)
The various errors are not fatal btw...

Cheers !
