### ISSUE TITLE
Add support of HTML/JS

### ISSUE THREAD

**Issue by redbaron** [baverman/snaked#9]
To make it really usable for Django dev please add HTML support

**Comment by baverman** [comment]
What kind of support do you need? I mean gtksourceview highlights html and js. What features do you expect?

**Comment by redbaron** [comment]
Take a look into PyCharm for example of really good Django support. For instance you can go to tag definition directly from django template

**Comment by baverman** [comment]
> For instance you can go to tag definition directly from django template

I'm planing code assist for django/jinja2 template variables for Django and Flask frameworks. Likely to the end of november.

Also in nearest time I'll implement support for GEdit's snippets plugin.

**Comment by jafd** [comment]
Any plans to have code-assist for Twisted? ;-)

**Comment by baverman** [comment]
Can you show some code and expected code-assist?
